# Generated by Django 4.2.26 on 2025-12-01 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comment_options'),
    ]

    operations = [
    ]
